name: ai_prompt_gallery
description: "AI prompt gallery project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.2
  animated_text_kit: ^4.2.2
  share_plus: ^11.0.0
  google_mobile_ads: ^6.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ai_microphone.gif
    - assets/career_icon.png
    - assets/coding_icon.png
    - assets/learning_icon.png
    - assets/lifestyle_icon.png
    - assets/marketing_icon.png
    - assets/my_prompts_icon.png
    - assets/productivity_icon.png
    - assets/work_icon.png
    - assets/writing_icon.png
    - assets/favorites_icon.png
    - assets/luminova_icon.png
    - assets/icons/app_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 23
